biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libro.urls')),
    path('prestamos/', include('prestamo.urls')),
    path('usuarios/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/libro/urls.py
from django.urls import path

from . import views

app_name = 'book_app'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('lista-libros/', views.BookListView.as_view(), name='list-book'),
    path('detalle-libro/<pk>/', views.BookDetailView.as_view(), name='detail-book'),
]

biblioteca/prestamo/urls.py
from django.urls import path

from . import views

app_name = 'loan_app'

urlpatterns = [
    path('lista-prestamos/', views.LoanListView.as_view(), name='loan-list'),
    path('detalle-prestamo/<pk>/', views.LoanDetailView.as_view(), name='detail-loan'),
]

biblioteca/templates/loan/loan_detail.html
{% extends 'base/base.html' %}

{% block title %}
    Prestamo de {{loan.book.title}} | Biblioteca
{% endblock title %}

{% block content %}
    {% include 'base/header.html' %}
    <div class="container p-5 my-5 border container-principal">
        <div class="row">
            <div class="col-lg-4">
                <img src="{{loan.book.cover_page.url}}" alt="{{loan.book.title}}" class="rounded">
            </div>
            <div class="col-lg-8">
                <h2 style="text-align: center;">{{loan.book.title}}</h2>
                <span class="badge bg-secondary" style="margin: 0 auto;">{{loan.book.date}}</span>
                <span class="badge bg-secondary">{{loan.book.category}}</span>
                <span class="badge bg-primary">{% for author in loan.book.authors.all %}{{author}}{% endfor %}</span>
                <div class="space"></div>
                <h5>{{loan.book.description}}</h5>
                <div class="space"></div>
                <div class="row">
                    <div class="col-lg-6">
                        <h5>Fecha de prestamo: {{loan.loan_date}}</h5>
                    </div>
                    <div class="col-lg-6">
                        {% if loan.returned %}
                            <h5>Ya devuelto: {{loan.return_date}}</h5>
                        {% else %}
                            <form action="" method="post">{% csrf_token %}
                            {{ form }}
                                <button class="btn btn-primary" type="submit">Devolver libro</button>
                            </form>

                        {% endif %}
                    </div>
                </div>
                    
            </div>
        </div>
    </div>
{% endblock content %}

biblioteca/templates/loan/loan_list.html
{% extends 'base/base.html' %}
{% block title %}
    Lista de prestamos | Biblioteca
{% endblock title %}
{% block content %}
    {% include 'base/header.html' %}
    <div class="container p-5 my-5 border container-principal">
        <div class="row">
            {% for book in list %}
            <div class="col-lg-4">
                <div class="card">
                    <img class="card-img-top" src="{{book.book.cover_page.url}}" alt="{{book.title}}">
                    <div class="card-body">
                      <h4 class="card-title">{{book.book.title}}</h4>
                       {% for author in book.book.authors.all %} <p>Autor: {{ author }}</p> {% endfor %}
                      <a href="{% url 'loan_app:detail-loan' book.id %}" class="btn btn-primary">Ver detalles del prestamo</a>
                    </div>
                  </div>
            </div>
            {% endfor %}
        </div>
    </div>

    
{% endblock content %}    