biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libro.urls')),
    path('prestamos/', include('prestamo.urls')),
    path('usuarios/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/libro/urls.py
from django.urls import path

from . import views

app_name = 'book_app'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('lista-libros/', views.BookListView.as_view(), name='list-book'),
    path('detalle-libro/<pk>/', views.BookDetailView.as_view(), name='detail-book'),
]

biblioteca/users/urls.py
from django.urls import path
from . import views


app_name = 'user_app'

urlpatterns = [
    path('registro/', views.UserRegisterFormView.as_view(), name='register'),
    path('iniciar-sesion/', views.LoginUserView.as_view(), name='login'),
    path('cerrar-sesion/', views.LogoutView.as_view(), name='logout'),
]

biblioteca/templates/book/book_detail.html
{% extends 'base/base.html' %}

{% block title %}
    {{book.title}} | Biblioteca
{% endblock title %}

{% block content %}
    {% include 'base/header.html' %}
    <div class="container p-5 my-5 border container-principal">
        <div class="row">
            <div class="col-lg-4">
                <img src="{{book.cover_page.url}}" alt="{{book.title}}" class="rounded">
            </div>
            <div class="col-lg-8">
                <h2 style="text-align: center;">{{book.title}}</h2>
                <span class="badge bg-secondary" style="margin: 0 auto;">{{book.date}}</span>
                <span class="badge bg-secondary">{{book.category}}</span>
                <span class="badge bg-primary">{% for author in book.authors.all %}{{author}}{% endfor %}</span>
                <div class="space"></div>
                <h5>{{book.description}}</h5>
                
                {% if user.username %}
                    <div class="space"></div>
                    <form action="" method="POST">
                        {% csrf_token %}
                        {{form}}
                        <button type="submit" class="btn btn-primary">Solicitar prestamo</button>    
                    </form>
                    
                {% else %}
                    <div class="space"></div>
                    <div class="alert alert-primary" style="text-align: center;">
                        Debe estar registrado para solicitar un prestamo a la biblioteca.
                        Si no esta registrado haga click <a href="{% url 'user_app:register'%}">aqui</a>
                    </div>
                {% endif %}
                    
            </div>
        </div>
    </div>
{% endblock content %}
    
    

biblioteca/templates/book/book_list.html
{% extends 'base/base.html' %}
{% block title %}
    Lista de libros | Biblioteca
{% endblock title %}
{% block content %}
    {% include 'base/header.html' %}
    <div class="container-fluid p-5 my-5 border container-principal">
        <form action="" method="get">
            {% csrf_token %}
            <div class="row">
                <div class="col-lg-3">

                </div>
                <div class="col-lg-7">
                    <input type="text" id="kword" name="kword" class="form-control" placeholder="Buscar por titulo...">
                </div>
                <div class="col-lg-2">
                    <button type="submit" class="btn btn-primary">Buscar</button>
                </div>
            </div>
        </form>
        <div class="space"></div>
        <div class="row">
            <div class="col-lg-2">
                <!-- Filtros -->
                <form action="" method="get">
                    {% csrf_token %}
                    {% for field in form %}
                        <label class="form-label">{{field.label}}</label>
                        {{field}}
                    {% endfor %}
                    <button class="btn btn-primary" type="submit">Filtrar</button>
                </form>
            </div>
            <div class="col-lg-10">
                <div class="row">
                    {% for book in list %}
                        <div class="col-lg-4">
                            <div class="card">
                                <img class="card-img-top" src="{{book.cover_page.url}}" alt="{{book.title}}">
                                <div class="card-body">
                                  <h4 class="card-title">{{book.title}}</h4>
                                   {% for author in book.authors.all %} <p>Autor: {{ author }}</p> {% endfor %}
                                  <a href="{% url 'book_app:detail-book' book.id %}" class="btn btn-primary">Ver detalles</a>
                                </div>
                              </div>
                        </div>
                    {% endfor %}         
                </div>
            </div>
        </div>
    </div>
{% endblock content %}
    
    