biblioteca/biblioteca/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('libro.urls')),
    path('prestamos/', include('prestamo.urls')),
    path('usuarios/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

biblioteca/libro/urls.py
from django.urls import path

from . import views

app_name = 'book_app'

urlpatterns = [
    path('', views.Index.as_view(), name='index'),
    path('lista-libros/', views.BookListView.as_view(), name='list-book'),
    path('detalle-libro/<pk>/', views.BookDetailView.as_view(), name='detail-book'),
]

biblioteca/prestamo/urls.py
from django.urls import path

from . import views

app_name = 'loan_app'

urlpatterns = [
    path('lista-prestamos/', views.LoanListView.as_view(), name='loan-list'),
    path('detalle-prestamo/<pk>/', views.LoanDetailView.as_view(), name='detail-loan'),
]

biblioteca/users/urls.py
from django.urls import path
from . import views


app_name = 'user_app'

urlpatterns = [
    path('registro/', views.UserRegisterFormView.as_view(), name='register'),
    path('iniciar-sesion/', views.LoginUserView.as_view(), name='login'),
    path('cerrar-sesion/', views.LogoutView.as_view(), name='logout'),
]

biblioteca/templates/base/base.html
<!DOCTYPE html> {% load static %}
<html lang="es">
<head>
  <title>{% block title %}{% endblock title %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.2/dist/js/bootstrap.bundle.min.js"></script>
  <link href="{% static 'styles/styles.css' %}" rel="stylesheet">
</head>
<body>
  
{% block content %}
{% endblock content %}
</body>
</html>

biblioteca/templates/base/header.html
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'book_app:index' %}">Biblioteca</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mynavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="mynavbar">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'book_app:list-book' %}">Lista de libros</a>
        </li>
        {% if user.username %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'loan_app:loan-list' %}">Lista de prestamos</a>
        </li>
        {% endif %}  
      </ul>
      {% if user.username %}
          <a href="{% url 'user_app:logout'%}" class="nav-link">Cerrar session</a>
      {% else %}
          <a href="{% url 'user_app:register'%}" class="nav-link">Registrarse</a>
          <a href="{% url 'user_app:login' %}" class="nav-link">Iniciar sesion</a>
      {% endif %}
    </div>
  </div>
</nav>

biblioteca/templates/base/index.html
{% extends 'base/base.html' %} {% load static %}
{% block title %}
    Inicio | Biblioteca
{% endblock title %}
{% block content %}
{% include 'base/header.html' %}
    <div class="container-fluid p-5 my-5 border container-principal">
        <img src="{% static 'img/biblio.jpg' %}" class="mx-auto d-block images">
        <div class="space"></div>
        <div class="alert alert-primary welcome">
            <h3>Bienvenidos!</h3>
            <h5>Bienvenidos a la mejor biblioteca de Santiago, aca podras pedir los libros
                que quieras a traves de nuestro famosisimo sistema de prestamos
            </h5>
        </div>
{% endblock content %}
    </div>